/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdmpayrollproject.Form.Manage;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import pdmpayrollproject.DBHandler.SQLRun;
import pdmpayrollproject.Form.OtherFunction.GeneratePayroll;
import pdmpayrollproject.Form.OtherFunction.GenerateSalary;

public class ManagePayroll extends javax.swing.JFrame {

    private int selectedID = 0;
 
    public ManagePayroll() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private boolean validateFields(String formType){
        if(formType.equals("edit") && !txtID.getText().equals("") && !txtName.getText().equals("") && !txtStatus.getText().equals("") && !txtDate.getText().equals("") && !txtAmount.getText().equals("")){
            return false;
        }
        else if (formType.equals("new") && (!txtID.getText().equals("") && !txtName.getText().equals("") && !txtStatus.getText().equals("") && !txtDate.getText().equals("") && !txtAmount.getText().equals(""))){
            return false;
        }
        else{
            return true;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnGeneratePayroll = new javax.swing.JButton();
        btnGenrateSalary = new javax.swing.JButton();
        btnUpdatePending = new javax.swing.JButton();
        btnUpdatePaid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Payroll Manage");

        jTable1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Employee Name", "Date", "Status", "Total Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnBack.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("ID");

        txtID.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("Name");

        txtName.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Date");

        txtDate.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Status");

        txtStatus.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setText("Total amount");

        txtAmount.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        btnGeneratePayroll.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnGeneratePayroll.setText("GENERATE PAYROLL THIS MONTH");
        btnGeneratePayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePayrollActionPerformed(evt);
            }
        });

        btnGenrateSalary.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnGenrateSalary.setText("GENERATE SALARY THIS MONTH");
        btnGenrateSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenrateSalaryActionPerformed(evt);
            }
        });

        btnUpdatePending.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnUpdatePending.setText("CHANGE STATUS TO PENDING");
        btnUpdatePending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePendingActionPerformed(evt);
            }
        });

        btnUpdatePaid.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnUpdatePaid.setText("CHANGE STATUS TO PAID");
        btnUpdatePaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePaidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenrateSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnGeneratePayroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnUpdatePaid)
                                .addComponent(btnUpdatePending))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(24, 24, 24)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnGenrateSalary, btnUpdatePaid, btnUpdatePending});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnGeneratePayroll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenrateSalary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdatePending)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdatePaid)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnReset)
                            .addComponent(btnUpdate))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        SQLRun objSQLRun = new SQLRun();
        String sql;
        ResultSet rs;
        
        sql = "SELECT * FROM payroll,employee WHERE payroll_employee_id = employee_id";
        rs = objSQLRun.sqlQuery(sql);
        
        try {
            while (rs.next()){
                String employee_id = rs.getString("employee_id");
                String employee_name = rs.getString("employee_name");
                String payroll_date = rs.getString("payroll_date");
                String payroll_status = rs.getString("payroll_status");
                String payroll_id = rs.getString("payroll_id");
                double salary = 0, allowance =0, bonus=0, deduction=0, total=0;
                                
                ResultSet rs2;
                
                //get salary
                sql = "SELECT * FROM salary WHERE salary_payroll_id = '"+payroll_id+"';";
                rs2 = objSQLRun.sqlQuery(sql);
                if (rs2.isBeforeFirst()){
                    rs2.next();
                    salary = rs2.getDouble("salary_amount");
                }
                
                //get allowance
                sql = "SELECT * FROM  allowance WHERE allowance_status = 'approved' AND allowance_payroll_id = '"+payroll_id+"';";
                rs2 = objSQLRun.sqlQuery(sql);
                if (rs2.isBeforeFirst()){
                    rs2.next();
                    allowance = rs2.getDouble("allowance_amount");
                }
                
                //get bonus
                sql = "SELECT * FROM bonus WHERE bonus_payroll_id = '"+payroll_id+"';";
                rs2 = objSQLRun.sqlQuery(sql);
                if (rs2.isBeforeFirst()){
                    rs2.next();
                    bonus = rs2.getDouble("bonus_amount");
                }
                
                //get deduction
                sql = "SELECT * FROM deduction WHERE deduction_payroll_id = '"+payroll_id+"';";
                rs2 = objSQLRun.sqlQuery(sql);
                if (rs2.isBeforeFirst()){
                    rs2.next();
                    deduction = rs2.getDouble("deduction_amount");
                }
                
                total = salary+bonus+allowance - deduction;
                
                model.addRow(new Object[]{employee_id,employee_name,payroll_date, payroll_status, total});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManagePayroll.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        btnUpdate.setEnabled(false);
        btnUpdatePaid.setEnabled(false);
        btnUpdatePending.setEnabled(false);

    }//GEN-LAST:event_formComponentShown

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
        new ManagePayroll().setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //get input
        if (validateFields("edit")){
            JOptionPane.showMessageDialog(null,"All fields are required");
        }
        else{
            int id = Integer.parseInt(txtID.getText());
            String status = txtStatus.getText();
            String date = txtDate.getText();  

            //Init sql connection
            SQLRun objSQLRun = new SQLRun();
            String sql;
            ResultSet rs;

            //Run sql
            sql = "UPDATE payroll "
                    + "SET payroll_date = '" + date
                    + "', payroll_status ='" + status
                    + "' WHERE payroll_id = '" + id + "'";

            System.out.println(sql);
            objSQLRun.sqlUpdate(sql);
            JOptionPane.showMessageDialog(null,"Updated Sucessfully");
            btnResetActionPerformed(evt); 
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
                // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        String id = model.getValueAt(index,0).toString();
        selectedID = Integer.parseInt(id);
        txtID.setText(id);
        
        String name = model.getValueAt(index,1).toString();
        txtName.setText(name);
        
        String date = model.getValueAt(index,2).toString();
        txtDate.setText(date);
        
        String status = model.getValueAt(index, 3).toString();
        txtStatus.setText(status);
        
        String amount = model.getValueAt(index, 4).toString();
        txtAmount.setText(amount);
        
        btnUpdate.setEnabled(true);  
        btnUpdatePending.setEnabled(true);  
        btnUpdatePaid.setEnabled(true);  
    }//GEN-LAST:event_jTable1MouseReleased

    private void btnGeneratePayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePayrollActionPerformed
        try {
            // TODO add your handling code here:
            new GeneratePayroll();
        } catch (SQLException ex) {
            Logger.getLogger(ManagePayroll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGeneratePayrollActionPerformed

    private void btnGenrateSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenrateSalaryActionPerformed
        try {
            // TODO add your handling code here:
            new GenerateSalary();
        } catch (SQLException ex) {
            Logger.getLogger(ManagePayroll.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGenrateSalaryActionPerformed

    private void btnUpdatePendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePendingActionPerformed
        // TODO add your handling code here:
            int id = Integer.parseInt(txtID.getText());
            String status = "pending";

            //Init sql connection
            SQLRun objSQLRun = new SQLRun();
            String sql;
            ResultSet rs;

            //Run sql
            sql = "UPDATE payroll "
                    + "SET payroll_status ='" + status
                    + "' WHERE payroll_id = '" + id + "'";

            System.out.println(sql);
            objSQLRun.sqlUpdate(sql);
            JOptionPane.showMessageDialog(null,"Updated Sucessfully");
            btnResetActionPerformed(evt); 
    }//GEN-LAST:event_btnUpdatePendingActionPerformed

    private void btnUpdatePaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePaidActionPerformed
        // TODO add your handling code here:
            int id = Integer.parseInt(txtID.getText());
            String status = "paid";

            //Init sql connection
            SQLRun objSQLRun = new SQLRun();
            String sql;
            ResultSet rs;

            //Run sql
            sql = "UPDATE payroll "
                    + "SET payroll_status ='" + status
                    + "' WHERE payroll_id = '" + id + "'";

            System.out.println(sql);
            objSQLRun.sqlUpdate(sql);
            JOptionPane.showMessageDialog(null,"Updated Sucessfully");
            btnResetActionPerformed(evt); 
    }//GEN-LAST:event_btnUpdatePaidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePayroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGeneratePayroll;
    private javax.swing.JButton btnGenrateSalary;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdatePaid;
    private javax.swing.JButton btnUpdatePending;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
