/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdmpayrollproject.Form.HR;

import pdmpayrollproject.DBHandler.SQLRun;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pdmpayrollproject.Form.Manage.ManageAllowance;
import pdmpayrollproject.Form.Manage.ManageBonus;
import pdmpayrollproject.Form.Manage.ManageDeduction;
import pdmpayrollproject.Form.Manage.ManageDepartment;
import pdmpayrollproject.Form.Manage.ManageEmployee;
import pdmpayrollproject.Form.Manage.ManageJob;
import pdmpayrollproject.Form.Manage.ManagePayroll;
import pdmpayrollproject.Form.Manage.ManagePosition;
import pdmpayrollproject.Form.Manage.ManageSalary;
import pdmpayrollproject.Form.OtherFunction.ChangePassword;
import pdmpayrollproject.Form.SignIn;

public class HRHome extends javax.swing.JFrame {

    /**
     * Creates new form HRHome
     */
    private SQLRun objSQLRun = new SQLRun();
    private int employeeID;
    
    
    public HRHome() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public HRHome(int id) throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        this.employeeID = id;
        
        //get the name of the Employee in the main page
        String sql = ("SELECT employee_name FROM `employee` where employee_id = '"+employeeID+"'");
        ResultSet rs = objSQLRun.sqlQuery(sql);
        rs.next();
        String name = rs.getString("employee_name");
        jLabel1.setText("Welcome "+name);
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        btnManageEmployee = new javax.swing.JButton();
        btnManagePayroll = new javax.swing.JButton();
        btnViewDepartment = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        btnViewDepartment1 = new javax.swing.JButton();
        btnManagePosition = new javax.swing.JButton();
        btnManageJob = new javax.swing.JButton();
        btnManageSalary = new javax.swing.JButton();
        btnManageAllowance = new javax.swing.JButton();
        btnManageBonus = new javax.swing.JButton();
        btnManageDeduction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setText("HOME PAGE");

        btnManageEmployee.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnManageEmployee.setText("MANAGE EMPLOYEE");
        btnManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeeActionPerformed(evt);
            }
        });

        btnManagePayroll.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnManagePayroll.setText("MANAGE PAYROLL");
        btnManagePayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePayrollActionPerformed(evt);
            }
        });

        btnViewDepartment.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnViewDepartment.setText("MANAGE DEPARTMENT");
        btnViewDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDepartmentActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCheck.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnCheck.setText("CHECK ATTENDANCE");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("WELCOME");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AVAILABLE FUNCTION :");

        btnChangePassword.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnChangePassword.setText("CHANGE PASSWORD");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnViewDepartment1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnViewDepartment1.setText("ADD NEW EMPLOYEE");
        btnViewDepartment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDepartment1ActionPerformed(evt);
            }
        });

        btnManagePosition.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnManagePosition.setText("MANAGE POSITION");
        btnManagePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePositionActionPerformed(evt);
            }
        });

        btnManageJob.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnManageJob.setText("MANAGE JOB");
        btnManageJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageJobActionPerformed(evt);
            }
        });

        btnManageSalary.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnManageSalary.setText("MANAGE SALARY");
        btnManageSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSalaryActionPerformed(evt);
            }
        });

        btnManageAllowance.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnManageAllowance.setText("MANAGE ALLOWANCE");
        btnManageAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAllowanceActionPerformed(evt);
            }
        });

        btnManageBonus.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnManageBonus.setText("MANAGE BONUS");
        btnManageBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBonusActionPerformed(evt);
            }
        });

        btnManageDeduction.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnManageDeduction.setText("MANAGE DEDUCTION");
        btnManageDeduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeductionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewDepartment1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnManagePayroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btnManagePosition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                                .addComponent(btnManageJob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(btnViewDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnManageAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnManageBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnManageDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnManageEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnManageSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(btnChangePassword)
                                    .addGap(74, 74, 74)
                                    .addComponent(btnCheck))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(317, 317, 317)
                                .addComponent(btnLogout))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageEmployee, btnManagePayroll, btnViewDepartment, btnViewDepartment1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDepartment1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManagePayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageSalary)
                    .addComponent(btnManageEmployee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageAllowance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageBonus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageJob)
                    .addComponent(btnManageDeduction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnManageEmployee, btnManagePayroll, btnViewDepartment, btnViewDepartment1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeeActionPerformed
        // TODO add your handling code here:
        new ManageEmployee().setVisible(true);
        
        
    }//GEN-LAST:event_btnManageEmployeeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int a = JOptionPane.showConfirmDialog(null,"Do you want to logout application?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
            setVisible(false);
            dispose(); 
            new SignIn().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        try {
            // TODO add your handling code here:
            new ChangePassword(employeeID).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(HRHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnViewDepartment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDepartment1ActionPerformed
        // TODO add your handling code here:
        new CreateAccount().setVisible(true);
    }//GEN-LAST:event_btnViewDepartment1ActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        SQLRun objSQLRun = new SQLRun();
        String sql;
        ResultSet rs;
        
        String today = new  SimpleDateFormat("YYYY-MM-dd").format(Calendar.getInstance().getTime());
        
        //Check if already checking attendance or not
        sql = "SELECT * FROM attendance WHERE attendance_date = '"+today+"' AND attendance_employee_id = '"+employeeID+"'";
        rs = objSQLRun.sqlQuery(sql);
        
        try {
            if (rs.isBeforeFirst() ) {
                JOptionPane.showMessageDialog(null,"You already checking attendance for today");
            }
            else{
                sql = "INSERT INTO attendance(attendance_date, attendance_employee_id) VALUE ('"+today+ "','"+employeeID+"');";
                objSQLRun.sqlUpdate(sql);
                JOptionPane.showMessageDialog(null,"Checking succesfully");
            }         
        } catch (SQLException ex) {
            Logger.getLogger(HRHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnViewDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDepartmentActionPerformed
        // TODO add your handling code here:
        new ManageDepartment().setVisible(true);
    }//GEN-LAST:event_btnViewDepartmentActionPerformed

    private void btnManagePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePositionActionPerformed
        // TODO add your handling code here:
        new ManagePosition().setVisible(true);
    }//GEN-LAST:event_btnManagePositionActionPerformed

    private void btnManageJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageJobActionPerformed
        // TODO add your handling code here:
        new ManageJob().setVisible(true);
    }//GEN-LAST:event_btnManageJobActionPerformed

    private void btnManagePayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePayrollActionPerformed
        // TODO add your handling code here:
        new ManagePayroll().setVisible(true);
    }//GEN-LAST:event_btnManagePayrollActionPerformed

    private void btnManageSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSalaryActionPerformed
        // TODO add your handling code here:
        new ManageSalary().setVisible(true);
    }//GEN-LAST:event_btnManageSalaryActionPerformed

    private void btnManageAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAllowanceActionPerformed
        // TODO add your handling code here:
        new ManageAllowance().setVisible(true);
    }//GEN-LAST:event_btnManageAllowanceActionPerformed

    private void btnManageBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBonusActionPerformed
        // TODO add your handling code here:
        new ManageBonus().setVisible(true);
    }//GEN-LAST:event_btnManageBonusActionPerformed

    private void btnManageDeductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeductionActionPerformed
        // TODO add your handling code here:
        new ManageDeduction().setVisible(true);
    }//GEN-LAST:event_btnManageDeductionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageAllowance;
    private javax.swing.JButton btnManageBonus;
    private javax.swing.JButton btnManageDeduction;
    private javax.swing.JButton btnManageEmployee;
    private javax.swing.JButton btnManageJob;
    private javax.swing.JButton btnManagePayroll;
    private javax.swing.JButton btnManagePosition;
    private javax.swing.JButton btnManageSalary;
    private javax.swing.JButton btnViewDepartment;
    private javax.swing.JButton btnViewDepartment1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
